[package]
name = "idna-2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
url={path="rust-url-edeaea7f1e8bd08148bcd535f921fbc645bce53e/url"}