[package]
name = "clap-3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap={path="clap-95144b7590bb4167bc469e4f5746fc0d560c0816"}
env_logger = "0.11.1"
log = "0.4.20"
