[package]
name = "textwrap-1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
textwrap = {path = "textwrap-607704a0d6bcf7d64dddad6d5df619dada208ec0"}