[package]
name = "regex-3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = {path = "regex-65ec58cbd4dd9a0fcfa0823876b7dd0bb1736bd1"}