[package]
name = "parking-lot-1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parking_lot = {path="parking_lot-04d6cfe2cac1d1db7385623865e9e6ed452ebf50"}
