[package]
name = "utils-1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
der={path="utils-der-v0.4.0/der"}
to_vec="0.1.0"
