[package]
name = "serde_json-2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = {path = "json-805f394f8b4165e4f365c27068eedc1d9cb6ac52"}