[package]
name = "rand-1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = {path = "rand-39a37f0ddfb07714b39c1fd9d8d140c6b02b6c53"}