[package]
name = "chrono-2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = {path = "chrono-e39346e2877b3a5445953f2bc5b64263cf46fc72"}