[package]
name = "serde_json-1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = {path = "json-1.0.63", features = ["raw_value"]}