[package]
name = "aho-corasick-1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aho-corasick={path="aho-corasick-39b029bb222eb04b03c9dfd7538c0fdb544fc579"}
