[package]
name = "idna-5"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
url={path="rust-url-a9ca033439001d05154dc4afd053570f4bfc0928"}