[package]
name = "time-2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = {path = "time-eb0045e7898ed6d357f33ebd618c1987741cf820"}