[package]
name = "clap-1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap={path="clap-cbc9c9dd44fc4be25c196213d508b9d2a9c282f3", features = ["derive"]}
