[package]
name = "num-traits-1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits={path="rust-smallvec-0.6.8"}